# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 19b32413b1bef4f6a81dd1a56727badc19ca95935f80dda16951b08cda85aa3e923e40294074190bfcacdfb6e0147d8970ddaa0f3d6511aea3c1f55433cdaaba

test:
  secret_key_base: a1c44a74e7c7eae4063c9c88eb1ec3193af5001d36772704e067afae459f0cfc93b1a662bf99d7240dd5c48008274387e0289ea5c507094d9b96416a64203bd9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
